name: Build, Test and Deploy Library app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: install dependencies
      run: npm install
    - name: install PlayWritght browsers
      run: npx playwright install
    - name: Start Backend
      run: npm run start-backend &
    - name: Start Frontend
      run: npm run start-frontend &
    - name: Execute UI Tests
      run: npm run test
