name: Build, Test and Deploy Library app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Change Backend to localhost
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js
    - name: Start Backend
      run: npm run start-backend &
    - name: Start Frontend
      run: npm run start-frontend &
    - name: Execute UI Tests
      run: npm run test
  
  deploy-backend:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy on Production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.Y_RENDER_BE_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true
  
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy on Production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.MY_RENDER_FE_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true